---
- name: Install ntp
  yum: state=present name=ntp

- name: Install wget
  yum: state=present name=wget

- name: start tnp
  service: name=ntpd state=started

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.all.disable_ipv6 = 1"

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.default.disable_ipv6 = 1"

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.lo.disable_ipv6 = 1"

- name: reload kernel settings
  shell: 'sysctl -e -p'

- name: disable huge page support
  shell: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
