---
- name: Install ntp
  yum: state=present name=ntp

- name: Install wget
  yum: state=present name=wget

- name: Install tree
  yum: state=present name=tree

- name: Install telnet
  yum: state=present name=telnet

- name: Install nmap
  yum: state=present name=nmap

- name: start ntp deamon
  service: name=ntpd state=started

- name: make ntp daemon start on boot
  shell: chkconfig ntpd on

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.all.disable_ipv6 = 1"

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.default.disable_ipv6 = 1"

- name: modify sysctl.conf
  lineinfile: dest=/etc/sysctl.conf line="net.ipv6.conf.lo.disable_ipv6 = 1"

- name: reload kernel settings
  shell: 'sysctl -e -p'

- name: disable huge page support
  shell: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'

- name: modify hostsfile
  lineinfile: dest=/etc/hosts regexp='^127.0.0.1' state=present line="127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4"

- name: modify hostsfile
  lineinfile: dest=/etc/hosts line="192.168.100.10 master.locallab.com"

- name: modify hostsfile
  lineinfile: dest=/etc/hosts line="192.168.100.20 slave1.locallab.com"

- name: modify hostsfile
  lineinfile: dest=/etc/hosts line="192.168.100.30 slave2.locallab.com"
