- name: create key for root user
  user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: setup authorized keys
  authorized_key: user=root key="{{ item }}"
  with_file:
    - roles/master-keys/files/id_rsa.pub
